# Generated by Django 6.0.3 on 2026-03-15 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField()),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('package_size', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True)),
                ('allergen_info', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('homepage', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NutritionFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serving_size', models.CharField(blank=True, max_length=120)),
                ('energy_kj', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('energy_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('saturates_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carbohydrates_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sugars_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fiber_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salt_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_facts', to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'nutrition facts',
            },
        ),
        migrations.CreateModel(
            name='ProductSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_text', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('scraped_at', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='catalog.product')),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supermarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.supermarket'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('supermarket', 'source_url'), name='unique_product_url_per_supermarket'),
        ),
    ]
