# Generated by Django 6.0.3 on 2026-03-15 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_seed_albert_heijn"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("catalog", "Catalog"),
                            ("bonus", "Bonus"),
                            ("category", "Category"),
                            ("brand", "Brand"),
                            ("listing", "Listing"),
                        ],
                        default="listing",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                ("last_crawled_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crawl_sources",
                        to="catalog.supermarket",
                    ),
                ),
            ],
            options={
                "ordering": ["supermarket__name", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="crawlsource",
            constraint=models.UniqueConstraint(
                fields=("supermarket", "url"),
                name="unique_crawl_source_url_per_supermarket",
            ),
        ),
    ]
