# Generated by Codex on 2026-03-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_seed_ah_crawl_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="nutri_score_grade",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="product",
            name="nutri_score_label",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="nutritionfacts",
            name="amount_column_label",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="nutritionfacts",
            name="declaration_basis",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="nutritionfacts",
            name="reference_intake_column_label",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="nutritionfacts",
            name="reference_intake_note",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="NutritionEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("label", models.CharField(max_length=255)),
                ("value_text", models.CharField(blank=True, max_length=255)),
                ("reference_intake_text", models.CharField(blank=True, max_length=64)),
                (
                    "nutrition_facts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="catalog.nutritionfacts",
                    ),
                ),
            ],
            options={"ordering": ["position", "id"]},
        ),
        migrations.AddConstraint(
            model_name="nutritionentry",
            constraint=models.UniqueConstraint(
                fields=("nutrition_facts", "position"),
                name="unique_nutrition_entry_position_per_factset",
            ),
        ),
    ]
