# Generated by Codex on 2026-03-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_product_nutri_score_and_nutritionentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("importer", models.CharField(max_length=50)),
                ("mode", models.CharField(max_length=50)),
                ("query", models.CharField(blank=True, max_length=120)),
                ("sort_on", models.CharField(blank=True, max_length=50)),
                ("start_page", models.PositiveIntegerField(default=0)),
                ("pages_visited", models.PositiveIntegerField(default=0)),
                ("rows_imported", models.PositiveIntegerField(default=0)),
                ("unique_products_added", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="completed", max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_runs",
                        to="catalog.supermarket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
