# Generated by Django 6.0.3 on 2026-03-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_category_scope_taxonomy_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutrition_last_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_unavailable',
            field=models.BooleanField(default=False),
        ),
    ]
