# Generated by Django 6.0.3 on 2026-03-15 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_plannerprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQualityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('llm', 'LLM'), ('manual', 'Manual'), ('paper', 'Paper'), ('web', 'Web'), ('sensor', 'Sensor')], default='llm', max_length=20)),
                ('source_name', models.CharField(default='default', max_length=120)),
                ('source_reference', models.URLField(blank=True)),
                ('is_estimated', models.BooleanField(default=True)),
                ('confidence_label', models.CharField(blank=True, max_length=20)),
                ('assumptions_text', models.TextField(blank=True)),
                ('storage_notes', models.TextField(blank=True)),
                ('ambient_days_min', models.PositiveIntegerField(blank=True, null=True)),
                ('ambient_days_max', models.PositiveIntegerField(blank=True, null=True)),
                ('refrigerated_days_min', models.PositiveIntegerField(blank=True, null=True)),
                ('refrigerated_days_max', models.PositiveIntegerField(blank=True, null=True)),
                ('frozen_days_min', models.PositiveIntegerField(blank=True, null=True)),
                ('frozen_days_max', models.PositiveIntegerField(blank=True, null=True)),
                ('nutrient_degradation_summary', models.TextField(blank=True)),
                ('nutrient_degradation_json', models.JSONField(blank=True, default=dict)),
                ('spoilage_summary', models.TextField(blank=True)),
                ('odor_notes', models.TextField(blank=True)),
                ('color_change_notes', models.TextField(blank=True)),
                ('texture_change_notes', models.TextField(blank=True)),
                ('visible_signs_json', models.JSONField(blank=True, default=list)),
                ('spoilage_processes_json', models.JSONField(blank=True, default=list)),
                ('airborne_molecules_json', models.JSONField(blank=True, default=list)),
                ('sensor_targets_json', models.JSONField(blank=True, default=list)),
                ('safety_risk_notes', models.TextField(blank=True)),
                ('discard_guidance', models.TextField(blank=True)),
                ('raw_response_text', models.TextField(blank=True)),
                ('raw_response_json', models.JSONField(blank=True, default=dict)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_profiles', to='catalog.product')),
            ],
            options={
                'ordering': ['product__name', 'source_type', 'source_name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'source_type', 'source_name'), name='unique_quality_profile_per_product_source')],
            },
        ),
    ]
