# Generated by Django 6.0.3 on 2026-07-30 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_productqualityprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('kind', models.CharField(choices=[('retailer', 'Retailer'), ('reference_db', 'Reference database'), ('llm', 'LLM'), ('manual', 'Manual'), ('sensor', 'Sensor')], default='retailer', max_length=20)),
                ('base_url', models.URLField(blank=True)),
                ('license_name', models.CharField(blank=True, max_length=120)),
                ('license_url', models.URLField(blank=True)),
                ('attribution_required', models.BooleanField(default=False)),
                ('attribution_text', models.TextField(blank=True)),
                ('trust_rank', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['trust_rank', 'name'],
            },
        ),
        migrations.AddField(
            model_name='supermarket',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supermarkets', to='catalog.datasource'),
        ),
        migrations.CreateModel(
            name='ProductIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_type', models.CharField(choices=[('gtin', 'GTIN / EAN barcode'), ('ah_webshop_id', 'AH webshop id'), ('ah_hq_id', 'AH HQ id'), ('off_barcode', 'OpenFoodFacts barcode'), ('internal', 'Other internal id')], max_length=30)),
                ('value', models.CharField(max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('match_method', models.CharField(choices=[('api', 'Reported by source API'), ('barcode', 'Barcode join'), ('fuzzy_name', 'Fuzzy name match'), ('manual', 'Manually confirmed')], default='api', max_length=30)),
                ('confidence_label', models.CharField(blank=True, max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='catalog.product')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_identifiers', to='catalog.datasource')),
            ],
            options={
                'ordering': ['product__name', 'source__trust_rank', 'id_type'],
                'indexes': [models.Index(fields=['id_type', 'value'], name='idx_identifier_type_value')],
                'constraints': [models.UniqueConstraint(fields=('product', 'source', 'id_type', 'value'), name='unique_identifier_per_product_source_type')],
            },
        ),
    ]
