# Generated by Django 6.0.3 on 2026-07-30 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_seed_data_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenFoodFactsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('brands', models.CharField(blank=True, max_length=255)),
                ('quantity', models.CharField(blank=True, max_length=120)),
                ('serving_size', models.CharField(blank=True, max_length=120)),
                ('categories_tags', models.JSONField(blank=True, default=list)),
                ('countries_tags', models.JSONField(blank=True, default=list)),
                ('labels_tags', models.JSONField(blank=True, default=list)),
                ('ingredients_text', models.TextField(blank=True)),
                ('allergens_text', models.TextField(blank=True)),
                ('additives_tags', models.JSONField(blank=True, default=list)),
                ('nutriscore_grade', models.CharField(blank=True, max_length=5)),
                ('nova_group', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('energy_kj', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('energy_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('saturates_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carbohydrates_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sugars_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fiber_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salt_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sodium_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('completeness', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('off_last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='off_products', to='catalog.datasource')),
            ],
            options={
                'ordering': ['barcode'],
                'indexes': [models.Index(fields=['off_last_modified_at'], name='idx_off_last_modified'), models.Index(fields=['content_hash'], name='idx_off_content_hash')],
            },
        ),
    ]
