# Generated by Django 6.0.3 on 2026-07-30 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_openfoodfactsproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionfacts',
            name='resolution_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='resolved_from_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_nutrition_facts', to='catalog.datasource'),
        ),
    ]
